/**
 * RiseBunny Language System - English
 * To add a new language: copy this file to dil/xx.js,
 * register it in dil/index.js `diller` object. Done!
 * Usage: const { t, getLang } = require('../dil'); t(lang, 'moderasyon.banYetki')
 */
module.exports = {
  kod: "en",
  isim: "English",
  ortak: {
    hata: "An error occurred, please try again.",
    yetki: "You need the **{yetki}** permission to use this command!",
    sahipSadece: "Only the bot owner can use this command!",
    yoneticiGerek: "Administrator permission is required for this command.",
    premiumGerek: "This command is for premium members only. Type `r!premium` or join our support server: https://dsc.gg/risebunny",
    bakimda: "The bot is currently under maintenance: **{sebep}**",
    dilSec: "Please specify a valid language: `tr` or `en`",
    dilOk: "Your language has been successfully set to **English**!",
    sunucuDilOk: "Server language has been set to **{dil}**!",
    sunucuDilGerek: "You need the **Manage Server** permission to change the server language!",
    sunucuDilBaslik: "Server Language",
    destek: "https://dsc.gg/risebunny",
    premiumReklam: "To use this command [Buy Premium](https://dsc.gg/risebunny)."
  },
  yardim: {
    baslik: "RiseBunny Help Menu",
    aciklama: "Hey {kullanici}! Thanks for using me!\nPrefix: **{prefix}** | Language: **EN** | Membership: **{uyelik}**\nMove my role to the top or some commands will not work!",
    kategoriler: "Categories",
    linkler: "Links",
    davetEt: "Invite Me",
    destekSunucu: "Support Server",
    guncelleme: "Changelog",
    premiumBaslik: "Premium Perks",
    premiumPerks: "+50% work bonus • Double bank interest • Daily premium bonus • Premium pets • Premium protection • Priority support",
    kategoriListe: {
      kullanici: "User commands",
      moderasyon: "Moderation commands",
      kayit: "Registration system",
      koruma: "Protection system",
      logo: "Logo system",
      cekilis: "Giveaway system",
      ticket: "Ticket system",
      ekonomi: "Economy system",
      abone: "Subscriber system",
      premium: "Premium system",
      yapayzeka: "AI system",
      eglence: "Fun commands"
    }
  },
  moderasyon: {
    banYetki: "You need the `Ban Members` permission to use this command!",
    banEtiket: "You must mention the person to ban!",
    banSahip: "I cannot ban my owner ;)",
    banOk: "{kullanici} has been banned.",
    kickYetki: "Unfortunately you are not authorized to use this command.",
    kickEtiket: "Please mention the person to kick!",
    kickOnay: "Do you confirm kicking {kullanici} from the server?",
    kickOk: "Confirmed! {kullanici} has been kicked!",
    kickIptal: "Operation cancelled!",
    muteOrnek: "Specify the user to mute. Example: **r!mute @RiseBunny 1hour Spam**",
    muteSure: "Specify how long the user should stay muted.",
    muteSahip: "I cannot mute my own owner ;)",
    silMiktar: "Specify the number of messages to delete (1-100).",
    silOk: "Deleted {adet} messages."
  },
  kayit: {
    isimYaz: "Please **type your name** to finish your registration.",
    yasYaz: "Hello {isim}, now **type your age.**",
    sadeceIsim: "**Type only your name.** *Not your age.*",
    isimGerek: "**You need to type your name, buddy!**",
    yasSayi: "**Type your age **`(number)`** only.**",
    kayitOk: "Registration completed successfully. Have fun **{isim}**",
    otomatikKayit: "Registration completed. You were **automatically** registered. Have fun **{isim}**"
  },
  koruma: {
    kufurUyari: "{kullanici}, **Swearing is forbidden on this server!**",
    kufurLog: "{kullanici}, **tried to swear!**",
    reklamUyari: "{kullanici}, **Advertising is forbidden on this server!**",
    reklamLog: "{kullanici}, **tried to advertise!**",
    spamUyari: "{kullanici}, **Spamming is forbidden on this server!**",
    acildi: "{sistem} protection system enabled.",
    kapatildi: "{sistem} protection system disabled."
  },
  raid: {
    embedBaslik: "🛡️ Raid Protection",
    acildi: "Raid protection has been enabled! Threshold: **{esik}** joins / 10s.",
    acildiRol: "Raid protection has been enabled! Threshold: **{esik}** joins / 10s, Verification Role: {rol}",
    kapatildi: "Raid protection has been disabled.",
    durumAcik: "Status: **Enabled**\nThreshold: **{esik}** joins / 10s\nVerification Role: {rol}\n\nTo disable: `{prefix}raid off` or click the button below.",
    durumKapali: "Status: **Disabled**\n\nTo enable: `{prefix}raid on [threshold] [@role]` or click the button below.",
    rolYok: "None",
    zatenAcik: "Raid protection is already enabled!",
    zatenKapali: "Raid protection is already disabled!",
    tespit: "🛡️ Raid detected! New accounts are being verified.",
    butonAc: "Enable",
    butonKapat: "Disable"
  },
  ekonomi: {
    yetersiz: "Insufficient balance! Needed: **{miktar}**, current: **{bakiye}**.",
    paraEklendi: "Added {miktar} coins to: {kullanici}",
    transferOk: "Sent {miktar} coins to {kullanici}.",
    gunlukOk: "You claimed your daily reward: **{miktar}**! Come back tomorrow.",
    gunlukBekle: "You already claimed your daily reward! Remaining: **{sure}**",
    calisOk: "You worked and earned **{miktar}**!",
    vipGerek: "You need {eksik} more to buy VIP."
  },
  ticket: {
    kanalYok: "Ticket channel is not set. To set it: {prefix}ticketayarla #channel",
    kanalOk: "Ticket channel set successfully: {kanal}",
    sadeceAdmin: "Only admins can use this command.",
    amacSor: "Please state your ticket reason.",
    amacBaslik: "Ticket Reason",
    hosgeldin: "Welcome! Staff will reply as soon as possible, please be patient.\nTo close the ticket: lock",
    kapatildi: "Ticket closed by {kullanici}.",
    tekrarAcildi: "Ticket re-opened by {kullanici}.",
    silinecek: "Ticket will be fully deleted in 5 seconds.",
    cooldown: "You can open one ticket every 5 seconds!"
  },
  premium: {
    aktif: "Your VIP membership has been activated for 30 days.",
    zaten: "You already have an active VIP membership.",
    verildi: "Premium given to {kullanici}. Duration: 30 days.",
    silindi: "User premium data deleted successfully!",
    degil: "This member is not a premium member!",
    etiketle: "Mention the user to give premium to.",
    durum: "Your premium status: **{durum}** | Remaining: **{kalan}**",
    aktifDurum: "Active",
    pasifDurum: "Inactive",
    sureDoldu: "User premium expired: {kullanici} ({id})"
  },
  karaliste: {
    engellisin: "You are blocked from using RiseBunny commands.\n**Reason:** {sebep}",
    eklendi: "{kullanici} added to blacklist. Reason: {sebep}",
    kaldirildi: "{kullanici} removed from blacklist."
  },
  ticketPanel: {
    baslik: "Create Support Request",
    aciklama: "Press the button below to open a ticket for support.",
    buton: "Open Ticket",
    modalBaslik: "Ticket reason",
    sebepEtiket: "What is your reason?"
  },
  kategoriler: {
    kullanici: "User commands",
    moderasyon: "Moderation commands",
    kayit: "Registration system",
    yapayzeka: "AI system",
    koruma: "Protection system",
    logo: "Logo system",
    cekilis: "Giveaway system",
    ticket: "Ticket system",
    ekonomi: "Economy system",
    abone: "Subscriber system",
    premium: "Premium system",
    eglence: "Fun commands",
    davet: "Invite system",
    genel: "General commands",
    sohbet: "Chat commands",
    site: "Website link",
    sahip: "Owner commands",
    seviye: "Level system",
  },
  komutlar: {
    "abone": { aciklama: "Gives the subscriber role.", kullanim: "subscribe @user" },
    "abonelog": { aciklama: "Sets the subscriber log channel.", kullanim: "subscribe-log #channel" },
    "abonerol": { aciklama: "Sets the subscriber role.", kullanim: "subscribe-role @role" },
    "abonerol-sistem": { aciklama: "Shows the subscriber system menu.", kullanim: "subscribe-system" },
    "abone-yetkili": { aciklama: "Sets the subscriber staff role.", kullanim: "subscribe-staff @role" },
    "afk": { aciklama: "Sets you as AFK.", kullanim: "afk <reason>" },
    "atatürk": { aciklama: "Sends an Atatürk picture.", kullanim: "atatuerk" },
    "pp": { aciklama: "Shows the avatar.", kullanim: "avatar [@user]" },
    "bakım": { aciklama: "Toggles maintenance mode. (Owner)", kullanim: "maintenance [reason]" },
    "mağaza-yönet": { aciklama: "Website shop: change prices, show/hide items (owner).", kullanim: "shop-manage" },
    "yedek": { aciklama: "Backs up the entire croxydb to your DM (owner).", kullanim: "backup" },
    "yedek-yükle": { aciklama: "Restores a full backup file (owner).", kullanim: "restore + file attachment" },
    "siterol": { aciklama: "Assign a site role to users (kurucu excluded, staff only).", kullanim: "siterol @user [IDs...]" },
    "kupon": { aciklama: "Button-based coupon manager: cash/pet/premium, timed/permanent, bot/site (owner).", kullanim: "coupon" },
    "kodoluştur": { aciklama: "Creates the V2 permanent coupon or redirects to the panel.", kullanim: "create-coupon [v2]" },
    "ban-koruma-sıfırla": { aciklama: "Resets ban protection.", kullanim: "ban-protection-reset" },
    "ban-koruma": { aciklama: "Enables ban protection.", kullanim: "ban-protection #channel" },
    "ban": { aciklama: "Bans the mentioned user.", kullanim: "ban @user [reason]" },
    "banka": { aciklama: "Shows your bank balance.", kullanim: "bank" },
    "bansay": { aciklama: "Shows the banned member count.", kullanim: "ban-count" },
    "beyazliste": { aciklama: "Removes a user from the blacklist.", kullanim: "whitelist <ID>" },
    "bilgisistemi": { aciklama: "Collected data, commands and deletion info.", kullanim: "datasystem" },
    "çal": { aciklama: "Steals money from a user.", kullanim: "steal @user" },
    "çalış": { aciklama: "Work and earn money.", kullanim: "work" },
    "çek": { aciklama: "Withdraws money from the bank.", kullanim: "withdraw <amount>" },
    "cf": { aciklama: "Coin flip game.", kullanim: "coinflip <amount|all>" },
    "kasa-aç": { aciklama: "CS case opening simulation.", kullanim: "open-case" },
    "davet": { aciklama: "Bot invite and support links.", kullanim: "invite" },
    "dil": { aciklama: "Sets the bot language.", kullanim: "language <tr/en> | language server <tr/en>" },
    "emojiler": { aciklama: "Lists the server emojis.", kullanim: "emojis" },
    "espri": { aciklama: "Tells a random joke.", kullanim: "joke" },
    "eval": { aciklama: "Executes code. (Owner)", kullanim: "eval <code>" },
    "gif-animal": { aciklama: "Sends a random animal gif.", kullanim: "animal-gif" },
    "günlük": { aciklama: "Claims your daily reward.", kullanim: "daily" },
    "gönder": { aciklama: "Sends money to a user.", kullanim: "send-money @user <amount>" },
    "haftalık": { aciklama: "Claims your weekly reward.", kullanim: "weekly" },
    "hatırlat": { aciklama: "Premium reminder: DMs you an embed when time is up.", kullanim: "remind <duration> <text> | list | delete <no>" },
    "giriş-çıkış-ayarla": { aciklama: "Sets the welcome channel.", kullanim: "welcome-set #channel" },
    "giriş-çıkış-kapat": { aciklama: "Disables welcome messages.", kullanim: "welcome-reset" },
    "iban": { aciklama: "Creates or shows the IBAN.", kullanim: "iban [@user]" },
    "istatistik": { aciklama: "Shows bot statistics.", kullanim: "stats" },
    "istek": { aciklama: "Sends a code request.", kullanim: "request <text>" },
    "alınacak-rol": { aciklama: "Sets the role taken on register.", kullanim: "unregistered-role @role" },
    "erkek-rol": { aciklama: "Sets the male role.", kullanim: "male-role @role" },
    "erkek": { aciklama: "Registers as male.", kullanim: "register-male @user name age" },
    "kayıt-hg": { aciklama: "Sets the register welcome channel.", kullanim: "register-welcome #channel" },
    "kayıt-kanal": { aciklama: "Sets the registration channel.", kullanim: "register-channel #channel" },
    "kayıtçı-rol": { aciklama: "Sets the registrar role.", kullanim: "registrar-role @role" },
    "kız-rol": { aciklama: "Sets the female role.", kullanim: "female-role @role" },
    "kız": { aciklama: "Registers as female.", kullanim: "register-female @user name age" },
    "kanal-koruma-sıfırla": { aciklama: "Resets channel protection.", kullanim: "channel-protection-reset" },
    "kanal-koruma": { aciklama: "Enables channel protection.", kullanim: "channel-protection #channel" },
    "karaliste-liste": { aciklama: "Shows the blacklist.", kullanim: "blacklist-list" },
    "karaliste": { aciklama: "Adds a user to the blacklist.", kullanim: "blacklist <ID> [reason]" },
    "para": { aciklama: "Shows wallet and bank info.", kullanim: "wallet [@user]" },
    "para-sıralama": { aciklama: "Shows the money leaderboard.", kullanim: "money-top" },
    "kick": { aciklama: "Kicks a user (with confirm).", kullanim: "kick @user" },
    "kuponkullan": { aciklama: "Redeems a coupon code.", kullanim: "redeem-coupon <code>" },
    "kuponoluştur": { aciklama: "Creates a new coupon.", kullanim: "create-coupon <amount>" },
    "koruma": { aciklama: "Toggles premium protection.", kullanim: "protection [off]" },
    "kullanıcibilgi": { aciklama: "Shows user info.", kullanim: "userinfo [@user]" },
    "küfürengel": { aciklama: "Toggles the swear filter.", kullanim: "swear-filter" },
    "küfürlog": { aciklama: "Sets the swear log channel.", kullanim: "swear-log #channel" },
    "lafat": { aciklama: "Roasts the mentioned user.", kullanim: "comeback @user" },
    "arrow": { aciklama: "Makes an arrow logo.", kullanim: "arrow-logo <text>" },
    "gold": { aciklama: "Makes a gold logo.", kullanim: "gold-logo <text>" },
    "graffiti": { aciklama: "Makes a graffiti logo.", kullanim: "graffiti-logo <text>" },
    "green": { aciklama: "Makes a green logo.", kullanim: "green-logo <text>" },
    "mc-skin": { aciklama: "Shows a Minecraft skin.", kullanim: "mc-skin <player>" },
    "mod-log": { aciklama: "Sets the mod-log channel.", kullanim: "mod-log #channel" },
    "mute": { aciklama: "Mutes a user for a while.", kullanim: "mute @user 10m [reason]" },
    "otorol-ayarla": { aciklama: "Sets the auto role.", kullanim: "autorole-set @role #channel" },
    "otorol-mesaj": { aciklama: "Sets the auto role message.", kullanim: "autorole-message <text>" },
    "otorol-mesaj-sıfırla": { aciklama: "Resets the auto role message.", kullanim: "autorole-message-reset" },
    "otorol-kapat": { aciklama: "Disables auto role.", kullanim: "autorole-reset" },
    "oylama": { aciklama: "Starts a poll.", kullanim: "poll <text>" },
    "para-ekle": { aciklama: "Adds money to a user. (Staff)", kullanim: "add-money @user <amount>" },
    "transfer": { aciklama: "Transfers money to an IBAN.", kullanim: "transfer <iban> <amount>" },
    "param": { aciklama: "Shows your balance.", kullanim: "balance" },
    "para-sil": { aciklama: "Removes money from a user. (Staff)", kullanim: "remove-money @user <amount>" },
    "pet": { aciklama: "Buys or sells a pet.", kullanim: "pet buy <type> / pet sell <no>" },
    "petlerim": { aciklama: "Shows your pets.", kullanim: "my-pets [@user]" },
    "ping": { aciklama: "Shows the bot latency.", kullanim: "ping" },
    "premium-al": { aciklama: "Buys premium with game coins.", kullanim: "buy-premium" },
    "premium": { aciklama: "Shows premium status.", kullanim: "premium" },
    "premium-sil": { aciklama: "Removes premium. (Owner)", kullanim: "remove-premium @user" },
    "premium-ver": { aciklama: "Gives premium. (Owner)", kullanim: "give-premium @user [days]" },
    "randompp": { aciklama: "Shows a random avatar.", kullanim: "random-avatar" },
    "reklamengel": { aciklama: "Toggles the ad filter.", kullanim: "ad-filter" },
    "reklamlog": { aciklama: "Sets the ad log channel.", kullanim: "ad-log #channel" },
    "rol-koruma-sıfırla": { aciklama: "Resets role protection.", kullanim: "role-protection-reset" },
    "rol-koruma": { aciklama: "Enables role protection.", kullanim: "role-protection #channel" },
    "bonus-ekle": { aciklama: "Adds invite bonus.", kullanim: "add-bonus @user <count>" },
    "davet-kanal": { aciklama: "Sets the invite channel.", kullanim: "invite-channel #channel" },
    "davet-kanal-sıfırla": { aciklama: "Resets the invite channel.", kullanim: "invite-channel-reset" },
    "davetleri-sıfırla": { aciklama: "Resets invites.", kullanim: "reset-invites @user" },
    "davetlerim": { aciklama: "Shows your invites.", kullanim: "my-invites" },
    "davet-rol": { aciklama: "Adds an invite role reward.", kullanim: "invite-role @role <count>" },
    "davet-sıfırla": { aciklama: "Resets the invite rank.", kullanim: "reset-invite" },
    "rütbeler": { aciklama: "Lists invite ranks.", kullanim: "ranks" },
    "davettop": { aciklama: "Shows the invite leaderboard.", kullanim: "invite-top" },
    "sa-as": { aciklama: "Toggles the greeting system.", kullanim: "greeting on/off" },
    "say": { aciklama: "Shows server info.", kullanim: "server-info" },
    "shard": { aciklama: "Shows shard info.", kullanim: "shard" },
    "sil": { aciklama: "Deletes messages.", kullanim: "clear <1-100>" },
    "snipe": { aciklama: "Shows the last deleted message.", kullanim: "snipe" },
    "sohbet-aç": { aciklama: "Opens the chat.", kullanim: "chat-open" },
    "sohbet-kapat": { aciklama: "Closes the chat.", kullanim: "chat-close" },
    "sonmesaj": { aciklama: "Shows the last message.", kullanim: "last-message" },
    "soygun": { aciklama: "Robs a user.", kullanim: "heist @user" },
    "spam-kapat": { aciklama: "Disables spam protection.", kullanim: "spam-off" },
    "spamkoruma": { aciklama: "Toggles spam protection.", kullanim: "spam-filter" },
    "sunucukur": { aciklama: "Sets up the server.", kullanim: "setup-server" },
    "sunuculara": { aciklama: "Shows the bot invite link.", kullanim: "invite-bot" },
    "sürelirol": { aciklama: "Gives a temporary role.", kullanim: "temp-role @user @role <time>" },
    "sürem": { aciklama: "Shows your VIP time left.", kullanim: "my-time" },
    "ticket": { aciklama: "Opens a support ticket.", kullanim: "ticket <reason> / ticket panel" },
    "ticketayarla": { aciklama: "Sets the ticket channel.", kullanim: "ticket-setup #channel" },
    "tkm": { aciklama: "Plays rock-paper-scissors.", kullanim: "rps <rock/paper/scissors>" },
    "komutlar": { aciklama: "Shows the total command count.", kullanim: "command-count" },
    "unbanall": { aciklama: "Unbans everyone.", kullanim: "unban-all" },
    "uyarı": { aciklama: "Warns a user.", kullanim: "warn @user [reason]" },
    "vip": { aciklama: "Shows your VIP time.", kullanim: "vip" },
    "vipsistemler": { aciklama: "Lists VIP systems.", kullanim: "vip-system" },
    "y-kayıt-erkek": { aciklama: "AI male registration setup.", kullanim: "ai-register-male @role" },
    "y-kayıt-kadın": { aciklama: "AI female registration setup.", kullanim: "ai-register-female @role" },
    "ykayıt-kanal": { aciklama: "Sets the AI register channel.", kullanim: "ai-register-channel #channel" },
    "ykayıt-kapat": { aciklama: "Closes AI registration.", kullanim: "ai-register-close" },
    "ykayıt-sistem": { aciklama: "Shows the AI register menu.", kullanim: "ai-register-system" },
    "ykayıt-tag": { aciklama: "Sets the AI register tag.", kullanim: "ai-register-tag <tag>" },
    "ykayıt-kayıtsız": { aciklama: "Sets the AI unregistered role.", kullanim: "ai-register-unregistered @role" },
    "y-koruma": { aciklama: "Toggles AI protection.", kullanim: "ai-protection" },
    "y-otosistem": { aciklama: "Auto sets up AI registration.", kullanim: "ai-autosetup" },
    "ekonomi": { aciklama: "Economy help menu.", kullanim: "economy-help" },
    "kayıtsistemi": { aciklama: "Registration help menu.", kullanim: "register-help" },
    "korumasistemi": { aciklama: "Protection help menu.", kullanim: "protection-help" },
    "kullanıcı": { aciklama: "User help menu.", kullanim: "user-help" },
    "logosistemi": { aciklama: "Logo help menu.", kullanim: "logo-help" },
    "moderasyon": { aciklama: "Moderation help menu.", kullanim: "moderation-help" },
    "çekilişsistemi": { aciklama: "Giveaway help menu.", kullanim: "giveaway-help" },
    "yardım": { aciklama: "Shows the help menu.", kullanim: "help [category]" },
    "yatır": { aciklama: "Deposits money to the bank.", kullanim: "deposit <amount>" },
    "zarat": { aciklama: "Rolls a dice.", kullanim: "dice" },
    "başlat": { aciklama: "Starts a giveaway.", kullanim: "giveaway-start #channel <time> <winners> <prize>" },
    "sonlandır": { aciklama: "Ends a giveaway.", kullanim: "giveaway-end <messageID>" },
    "reroll": { aciklama: "Rerolls a giveaway.", kullanim: "giveaway-reroll <messageID>" },
    "öneri": { aciklama: "Sends a suggestion.", kullanim: "suggest <text>" },
    "üyedurum": { aciklama: "Shows the member count.", kullanim: "member-count" },
    "seviye": { aciklama: "Shows your level and XP card.", kullanim: "level [@user]" },
    "seviye-ödül": { aciklama: "Lists level rewards and sets role rewards.", kullanim: "level-reward [list|role <level> @role|delete <level>]" },
    "seviye-sıralama": { aciklama: "Shows the top 10 users by level (image).", kullanim: "level-top" },
    "günlük-ödül": { aciklama: "Daily reward that grows with your streak.", kullanim: "daily-streak" },
    "anket-gelişmiş": { aciklama: "Starts a timed button/reaction poll.", kullanim: "advanced-poll <time> <question> | <option1> | <option2>" },
    "çekiliş-şart": { aciklama: "Giveaway with invite/role requirement.", kullanim: "giveaway-requirement #channel <time> <winners> <prize> --davet <count> / --rol @role" },
    "raid-koruma": { aciklama: "Automatic verification and protection when many accounts join quickly.", kullanim: "raid on [threshold] [@role] | raid off | raid" },
    "raid": { aciklama: "Automatic verification and protection when many accounts join quickly.", kullanim: "raid on [threshold] [@role] | raid off | raid" },
    "market": { aciklama: "Marketplace to buy/sell pets.", kullanim: "market list | sell <petNo> <price> | buy <id> | cancel <id>" },
    "not": { aciklama: "Personal notes.", kullanim: "note add <text> | list | delete <no> | clear" },
    "isim-log": { aciklama: "Logs nickname changes.", kullanim: "nickname-log #channel | off" },
    "çevir": { aciklama: "Translates text to another language.", kullanim: "translate <target> <text>" },
    "slot": { aciklama: "Slot machine game.", kullanim: "slot <amount|all>" },
    "blackjack": { aciklama: "Blackjack (21) game.", kullanim: "blackjack <amount|all>" },
    "rulet": { aciklama: "Roulette game.", kullanim: "roulette <amount> <red/black/green/number>" },
    "faiz": { aciklama: "Daily interest on your bank balance.", kullanim: "interest" },
    "piyango": { aciklama: "Buy a lottery ticket and win the pool.", kullanim: "lottery [buy | draw]" },
    "meslek": { aciklama: "Choose a job and earn money.", kullanim: "job [select <job> | work]" },
    "envanter": { aciklama: "Shows all your items and stats.", kullanim: "inventory" },
    "premium-panel": { aciklama: "Shows premium perks.", kullanim: "premium-panel" },
    "kasa": { aciklama: "Personal vault that can't be stolen.", kullanim: "vault [deposit <amount> | withdraw <amount>]" },
    "günlük-bonus": { aciklama: "Premium-only daily bonus.", kullanim: "daily-bonus" },
  },
  sistem: {
    yonetici: "You need the **Administrator** permission to use this command!",
    mesajYonet: "This command requires the Manage Messages permission.",
    sunucuYonet: "You need the **Manage Server** permission to use this command!",
    sunucuSahibi: "You must be the **Server Owner** to use this command!",
    yetkiYok: "You do not have the required permission to use this command.",
    kullaniciBelirt: "You must mention a user.",
    rolBelirt: "You must mention a role.",
    kanalBelirt: "You must mention a channel.",
    acildi: "{sistem} has been enabled.",
    kapatildi: "{sistem} has been disabled.",
    ayarlandi: "{sistem} has been set successfully!",
    sifirlandi: "{sistem} has been reset successfully!",
    ayarlanmamis: "{sistem} is not set!",
    belirt: "You must specify {sistem}!",
    premiumBaslik: "Not a Premium Member",
    hataBaslik: "**ERROR**",
    sebep: "Reason",
    kullanici: "User",
    kanal: "Channel",
    mesaj: "Message",
    sonuc: "Result",
    eylem: "Action",
    isim: "Name",
    bilinmiyor: "Unknown"
  },
  kayitSistem: {
    kayitciGerek: "You need the {rol} role to use this command!",
    kanalOzel: "You can only use this command in the {kanal} channel!",
    kurulumYok: "Registration system is not fully set up! Please set the roles and channel first.",
    erkekKayit: "Male Registration",
    kizKayit: "Female Registration",
    kayitEden: "Registrar",
    kayitEdilen: "Registered user",
    isim: "Name",
    yas: "Age",
    isimBelirt: "You must specify a name!",
    yasBelirt: "You must specify an age!",
    rolSec: "Please mention the {tur} role!",
    rolAyarlandi: "{tur} role has been set to {rol} successfully!",
    rolSifirlandi: "{tur} role has been reset successfully!",
    kanalAyarlandi: "Registration channel has been set to {kanal}!",
    kanalSifirlandi: "Registration channel has been reset successfully!",
    kanalBelirt: "Please mention the registration channel!",
    hgAyarlandi: "Welcome channel has been set to {kanal}!",
    hgSifirlandi: "Welcome channel has been reset successfully!",
    hgBelirt: "Please mention the welcome channel!",
    alinacakAyarlandi: "Auto-taken role on register has been set to {rol} successfully!",
    alinacakSifirlandi: "Auto-taken role on register has been reset!",
    alinacakBelirt: "Please mention the role to take on register!",
    kayitciAyarlandi: "Registrar role has been set to {rol} successfully!",
    kayitciSifirlandi: "Registrar role has been reset successfully!",
    kayitciBelirt: "Please mention the registrar role to set!",
    erkek: "Male",
    kiz: "Female",
    kayitci: "Registrar",
    alinacak: "Role to take",
    kayitBasarili: "{uye} has been registered successfully! Have fun!"
  },
  onay: {
    baslik: 'Data Processing Consent',
    aciklama: 'To use commands, first pick your language, then read the docs below and accept.',
    dokuman: '📄 Documentation',
    gizlilik: '🔒 Privacy Policy',
    kosullar: '📜 Terms of Service',
    kabulEt: '✅ Save & Accept',
    reddet: '❌ I Decline',
    kabulOk: '✅ Consent saved! You can now use commands.',
    redBilgi: 'Consent is required to use commands. Press **Save & Accept** in the language menu.',
    gerekli: 'You must give data processing consent first! Press **Save & Accept** in the language menu. (r!dil)',
  },
};