/**
 * RiseBunny Merkezi Komut Sozlugu
 * - Canonical ad = komut dosyasindaki help.name (Turkce, kucuk harf).
 * - Her komutun kategorisi + Ingilizce adi/aliaslari burada.
 * - Turkce ad/aliaslar komut dosyalarindan gelir (tek kaynak).
 * - Cozumleme her iki dilde de calisir; GOSTERIM kullanicinin dilindedir.
 * - Yeni komut ekleyince buraya 1 satir ekle: ["ad", "kategori", "en-ad", ["en-alias"]]
 */
const KOMUTLAR = {
  "abone": { kat: "abone", en: "subscribe", enAlias: ["sub"] },
  "abonelog": { kat: "abone", en: "subscribe-log", enAlias: ["sub-log"] },
  "abonerol": { kat: "abone", en: "subscribe-role", enAlias: ["sub-role"] },
  "abonerol-sistem": { kat: "abone", en: "subscribe-system", enAlias: ["sub-system"] },
  "abone-yetkili": { kat: "abone", en: "subscribe-staff", enAlias: ["sub-staff"] },
  "afk": { kat: "kullanici", en: "afk", enAlias: ["brb"] },
  "atatürk": { kat: "eglence", en: "atatuerk", enAlias: ["ataturk"] },
  "pp": { kat: "kullanici", en: "avatar", enAlias: ["pfp"] },
  "bakım": { kat: "sahip", en: "maintenance", enAlias: ["maintain"] },
  "mağaza-yönet": { kat: "sahip", en: "shop-manage", enAlias: ["shopmanage"] },
  "yedek": { kat: "sahip", en: "backup", enAlias: ["yedek-al"] },
  "yedek-yükle": { kat: "sahip", en: "restore", enAlias: ["yedek-yukle"] },
  "kupon": { kat: "sahip", en: "coupon", enAlias: ["coupon-manage"] },
  "ban-koruma-sıfırla": { kat: "koruma", en: "ban-protection-reset", enAlias: ["banpreset"] },
  "ban-koruma": { kat: "koruma", en: "ban-protection", enAlias: ["banprotect"] },
  "ban": { kat: "moderasyon", en: "ban", enAlias: ["banish"] },
  "banka": { kat: "ekonomi", en: "bank", enAlias: ["vault"] },
  "bansay": { kat: "moderasyon", en: "ban-count", enAlias: ["bans"] },
  "beyazliste": { kat: "koruma", en: "whitelist", enAlias: ["unblacklist"] },
  "çal": { kat: "ekonomi", en: "steal", enAlias: ["rob"] },
  "çalış": { kat: "ekonomi", en: "work", enAlias: ["job"] },
  "çek": { kat: "ekonomi", en: "withdraw", enAlias: ["with"] },
  "cf": { kat: "ekonomi", en: "coinflip", enAlias: ["flip"] },
  "kasa-aç": { kat: "ekonomi", en: "open-case", enAlias: ["case"] },
  "davet": { kat: "genel", en: "invite", enAlias: ["inv"] },
  "dil": { kat: "genel", en: "language", enAlias: ["lang"] },
  "emojiler": { kat: "kullanici", en: "emojis", enAlias: ["emojilist"] },
  "espri": { kat: "eglence", en: "joke", enAlias: ["funny"] },
  "eval": { kat: "sahip", en: "eval", enAlias: ["run"] },
  "gif-animal": { kat: "eglence", en: "animal-gif", enAlias: ["animal"] },
  "günlük": { kat: "ekonomi", en: "daily", enAlias: ["day"] },
  "gönder": { kat: "ekonomi", en: "send-money", enAlias: ["givemoney"] },
  "haftalık": { kat: "ekonomi", en: "weekly", enAlias: ["week"] },
  "hatırlat": { kat: "kullanici", en: "remind", enAlias: ["reminder"] },
  "giriş-çıkış-ayarla": { kat: "genel", en: "welcome-set", enAlias: ["wset"] },
  "giriş-çıkış-kapat": { kat: "genel", en: "welcome-reset", enAlias: ["wreset"] },
  "iban": { kat: "ekonomi", en: "iban", enAlias: ["bank-account"] },
  "istatistik": { kat: "genel", en: "stats", enAlias: ["botstats"] },
  "istek": { kat: "genel", en: "request", enAlias: ["requestcode"] },
  "alınacak-rol": { kat: "kayit", en: "unregistered-role", enAlias: ["unreg-role"] },
  "erkek-rol": { kat: "kayit", en: "male-role", enAlias: ["mrole"] },
  "erkek": { kat: "kayit", en: "register-male", enAlias: ["reg-male"] },
  "kayıt-hg": { kat: "kayit", en: "register-welcome", enAlias: ["reg-welcome"] },
  "kayıt-kanal": { kat: "kayit", en: "register-channel", enAlias: ["reg-channel"] },
  "kayıtçı-rol": { kat: "kayit", en: "registrar-role", enAlias: ["registrar"] },
  "kız-rol": { kat: "kayit", en: "female-role", enAlias: ["frole"] },
  "kız": { kat: "kayit", en: "register-female", enAlias: ["reg-female"] },
  "kanal-koruma-sıfırla": { kat: "koruma", en: "channel-protection-reset", enAlias: ["chanpreset"] },
  "kanal-koruma": { kat: "koruma", en: "channel-protection", enAlias: ["chanprotect"] },
  "karaliste-liste": { kat: "koruma", en: "blacklist-list", enAlias: ["blist"] },
  "karaliste": { kat: "koruma", en: "blacklist", enAlias: ["block"] },
  "para": { kat: "ekonomi", en: "wallet", enAlias: ["money"] },
  "para-sıralama": { kat: "ekonomi", en: "money-top", enAlias: ["rich"] },
  "kick": { kat: "moderasyon", en: "kick", enAlias: ["boot"] },
  "kuponkullan": { kat: "ekonomi", en: "redeem-coupon", enAlias: ["redeem"] },
  "kuponoluştur": { kat: "ekonomi", en: "create-coupon", enAlias: ["coupon"] },
  "koruma": { kat: "koruma", en: "protection", enAlias: ["guard"] },
  "kullanıcibilgi": { kat: "kullanici", en: "userinfo", enAlias: ["whois"] },
  "küfürengel": { kat: "koruma", en: "swear-filter", enAlias: ["badword"] },
  "küfürlog": { kat: "koruma", en: "swear-log", enAlias: ["badword-log"] },
  "lafat": { kat: "eglence", en: "comeback", enAlias: ["diss"] },
  "arrow": { kat: "logo", en: "arrow-logo", enAlias: ["arrow"] },
  "gold": { kat: "logo", en: "gold-logo", enAlias: ["gold"] },
  "graffiti": { kat: "logo", en: "graffiti-logo", enAlias: ["graffiti"] },
  "green": { kat: "logo", en: "green-logo", enAlias: ["green"] },
  "mc-skin": { kat: "kullanici", en: "mc-skin", enAlias: ["skin"] },
  "mod-log": { kat: "moderasyon", en: "mod-log", enAlias: ["logs"] },
  "mute": { kat: "moderasyon", en: "mute", enAlias: ["silence"] },
  "otorol-ayarla": { kat: "genel", en: "autorole-set", enAlias: ["arset"] },
  "otorol-mesaj": { kat: "genel", en: "autorole-message", enAlias: ["armsg"] },
  "otorol-mesaj-sıfırla": { kat: "genel", en: "autorole-message-reset", enAlias: ["armsg-reset"] },
  "otorol-kapat": { kat: "genel", en: "autorole-reset", enAlias: ["arreset"] },
  "oylama": { kat: "eglence", en: "poll", enAlias: ["vote"] },
  "para-ekle": { kat: "ekonomi", en: "add-money", enAlias: ["addmoney"] },
  "transfer": { kat: "ekonomi", en: "transfer", enAlias: ["pay"] },
  "param": { kat: "ekonomi", en: "balance", enAlias: ["bal"] },
  "para-sil": { kat: "ekonomi", en: "remove-money", enAlias: ["takemoney"] },
  "pet": { kat: "ekonomi", en: "pet", enAlias: ["pets"] },
  "petlerim": { kat: "ekonomi", en: "my-pets", enAlias: ["mypets"] },
  "ping": { kat: "genel", en: "ping", enAlias: ["latency"] },
  "premium-al": { kat: "premium", en: "buy-premium", enAlias: ["getpremium"] },
  "premium": { kat: "premium", en: "premium", enAlias: ["vip-status"] },
  "premium-sil": { kat: "premium", en: "remove-premium", enAlias: ["delpremium"] },
  "premium-ver": { kat: "premium", en: "give-premium", enAlias: ["addpremium"] },
  "randompp": { kat: "kullanici", en: "random-avatar", enAlias: ["randompfp"] },
  "reklamengel": { kat: "koruma", en: "ad-filter", enAlias: ["linkfilter"] },
  "reklamlog": { kat: "koruma", en: "ad-log", enAlias: ["linklog"] },
  "rol-koruma-sıfırla": { kat: "koruma", en: "role-protection-reset", enAlias: ["rolepreset"] },
  "rol-koruma": { kat: "koruma", en: "role-protection", enAlias: ["roleprotect"] },
  "bonus-ekle": { kat: "davet", en: "add-bonus", enAlias: ["invite-bonus"] },
  "davet-kanal": { kat: "davet", en: "invite-channel", enAlias: ["inv-channel"] },
  "davet-kanal-sıfırla": { kat: "davet", en: "invite-channel-reset", enAlias: ["inv-channel-reset"] },
  "davetleri-sıfırla": { kat: "davet", en: "reset-invites", enAlias: ["inv-reset"] },
  "davetlerim": { kat: "davet", en: "my-invites", enAlias: ["myinv"] },
  "davet-rol": { kat: "davet", en: "invite-role", enAlias: ["inv-role"] },
  "davet-sıfırla": { kat: "davet", en: "reset-invite", enAlias: ["inv-wipe"] },
  "rütbeler": { kat: "davet", en: "ranks", enAlias: ["inv-ranks"] },
  "davettop": { kat: "davet", en: "invite-top", enAlias: ["invtop"] },
  "sa-as": { kat: "koruma", en: "greeting", enAlias: ["saas"] },
  "say": { kat: "genel", en: "server-info", enAlias: ["sinfo"] },
  "shard": { kat: "genel", en: "shard", enAlias: ["shardinfo"] },
  "sil": { kat: "moderasyon", en: "clear", enAlias: ["purge"] },
  "snipe": { kat: "kullanici", en: "snipe", enAlias: ["deleted"] },
  "sohbet-aç": { kat: "sohbet", en: "chat-open", enAlias: ["unlock"] },
  "sohbet-kapat": { kat: "sohbet", en: "chat-close", enAlias: ["lock"] },
  "sonmesaj": { kat: "kullanici", en: "last-message", enAlias: ["lastmsg"] },
  "soygun": { kat: "ekonomi", en: "heist", enAlias: ["robbery"] },
  "spam-kapat": { kat: "koruma", en: "spam-off", enAlias: ["antispam-off"] },
  "spamkoruma": { kat: "koruma", en: "spam-filter", enAlias: ["antispam"] },
  "sunucukur": { kat: "moderasyon", en: "setup-server", enAlias: ["setup"] },
  "sunuculara": { kat: "genel", en: "invite-bot", enAlias: ["addbot"] },
  "sürelirol": { kat: "genel", en: "temp-role", enAlias: ["timerole"] },
  "sürem": { kat: "ekonomi", en: "my-time", enAlias: ["mytime"] },
  "ticket": { kat: "ticket", en: "ticket", enAlias: ["support"] },
  "ticketayarla": { kat: "ticket", en: "ticket-setup", enAlias: ["ticketset"] },
  "tkm": { kat: "eglence", en: "rps", enAlias: ["rockpaperscissors"] },
  "komutlar": { kat: "genel", en: "command-count", enAlias: ["cmdcount"] },
  "unbanall": { kat: "moderasyon", en: "unban-all", enAlias: ["pardonall"] },
  "uyarı": { kat: "moderasyon", en: "warn", enAlias: ["warning"] },
  "vip": { kat: "ekonomi", en: "vip", enAlias: ["vip-time"] },
  "vipsistemler": { kat: "premium", en: "vip-system", enAlias: ["vipsys"] },
  "y-kayıt-erkek": { kat: "yapayzeka", en: "ai-register-male", enAlias: ["ai-male"] },
  "y-kayıt-kadın": { kat: "yapayzeka", en: "ai-register-female", enAlias: ["ai-female"] },
  "ykayıt-kanal": { kat: "yapayzeka", en: "ai-register-channel", enAlias: ["ai-channel"] },
  "ykayıt-kapat": { kat: "yapayzeka", en: "ai-register-close", enAlias: ["ai-close"] },
  "ykayıt-sistem": { kat: "yapayzeka", en: "ai-register-system", enAlias: ["ai-system"] },
  "ykayıt-tag": { kat: "yapayzeka", en: "ai-register-tag", enAlias: ["ai-tag"] },
  "ykayıt-kayıtsız": { kat: "yapayzeka", en: "ai-register-unregistered", enAlias: ["ai-unreg"] },
  "y-koruma": { kat: "yapayzeka", en: "ai-protection", enAlias: ["aiguard"] },
  "y-otosistem": { kat: "yapayzeka", en: "ai-autosetup", enAlias: ["ai-setup"] },
  "ekonomi": { kat: "yardim", en: "economy-help", enAlias: ["ecohelp"] },
  "kayıtsistemi": { kat: "yardim", en: "register-help", enAlias: ["reghelp"] },
  "korumasistemi": { kat: "yardim", en: "protection-help", enAlias: ["guardhelp"] },
  "kullanıcı": { kat: "yardim", en: "user-help", enAlias: ["uhelp"] },
  "logosistemi": { kat: "yardim", en: "logo-help", enAlias: ["logohelp"] },
  "moderasyon": { kat: "yardim", en: "moderation-help", enAlias: ["modhelp"] },
  "çekilişsistemi": { kat: "yardim", en: "giveaway-help", enAlias: ["ghelp"] },
  "yardım": { kat: "genel", en: "help", enAlias: ["assist"] },
  "yatır": { kat: "ekonomi", en: "deposit", enAlias: ["dep"] },
  "zarat": { kat: "eglence", en: "dice", enAlias: ["roll"] },
  "başlat": { kat: "cekilis", en: "giveaway-start", enAlias: ["gstart"] },
  "sonlandır": { kat: "cekilis", en: "giveaway-end", enAlias: ["gend"] },
  "reroll": { kat: "cekilis", en: "giveaway-reroll", enAlias: ["greroll"] },
  "öneri": { kat: "genel", en: "suggest", enAlias: ["idea"] },
  "üyedurum": { kat: "genel", en: "member-count", enAlias: ["members"] },
  "seviye": { kat: "seviye", en: "level", enAlias: ["rank", "xp"] },
  "seviye-ödül": { kat: "seviye", en: "level-reward", enAlias: ["levelrewards"] },
  "seviye-sıralama": { kat: "seviye", en: "level-top", enAlias: ["levelsiralama", "leveltop", "seviyetop"] },
  "günlük-ödül": { kat: "ekonomi", en: "daily-streak", enAlias: ["streak"] },
  "anket-gelişmiş": { kat: "eglence", en: "advanced-poll", enAlias: ["poll-advanced"] },
  "çekiliş-şart": { kat: "cekilis", en: "giveaway-requirement", enAlias: ["greq"] },
  "raid-koruma": { kat: "koruma", en: "raid-protection", enAlias: ["antiraid", "raid", "raidkoruma"] },
  "raid": { kat: "koruma", en: "raid", enAlias: ["raid-protection", "antiraid", "raidkoruma"] },
  "market": { kat: "ekonomi", en: "market", enAlias: ["marketplace"] },
  "not": { kat: "kullanici", en: "note", enAlias: ["notes"] },
  "isim-log": { kat: "moderasyon", en: "nickname-log", enAlias: ["nicklog"] },
  "çevir": { kat: "yapayzeka", en: "translate", enAlias: ["translator"] },
  "slot": { kat: "ekonomi", en: "slot", enAlias: ["slots"] },
  "blackjack": { kat: "ekonomi", en: "blackjack", enAlias: ["bj", "21"] },
  "rulet": { kat: "ekonomi", en: "roulette", enAlias: ["roulette"] },
  "faiz": { kat: "ekonomi", en: "interest", enAlias: ["bank-interest"] },
  "piyango": { kat: "ekonomi", en: "lottery", enAlias: ["loto"] },
  "meslek": { kat: "ekonomi", en: "job", enAlias: ["work-job"] },
  "envanter": { kat: "ekonomi", en: "inventory", enAlias: ["inv"] },
  "premium-panel": { kat: "premium", en: "premium-panel", enAlias: ["premium-perks"] },
  "kasa": { kat: "ekonomi", en: "vault", enAlias: ["safe"] },
  "günlük-bonus": { kat: "premium", en: "daily-bonus", enAlias: ["premium-bonus"] },
};

const KATEGORILER = [
  { id: "kullanici", emoji: "👤", tr: "Kullanıcı", en: "User" },
  { id: "moderasyon", emoji: "🛡️", tr: "Moderasyon", en: "Moderation" },
  { id: "kayit", emoji: "📝", tr: "Kayıt", en: "Registration" },
  { id: "yapayzeka", emoji: "🤖", tr: "Yapay Zeka", en: "AI" },
  { id: "koruma", emoji: "🔒", tr: "Koruma", en: "Protection" },
  { id: "logo", emoji: "🎨", tr: "Logo", en: "Logo" },
  { id: "cekilis", emoji: "🎉", tr: "Çekiliş", en: "Giveaway" },
  { id: "ticket", emoji: "🎫", tr: "Ticket", en: "Ticket" },
  { id: "ekonomi", emoji: "💰", tr: "Ekonomi", en: "Economy" },
  { id: "abone", emoji: "⭐", tr: "Abone", en: "Subscriber" },
  { id: "premium", emoji: "💎", tr: "Premium", en: "Premium" },
  { id: "eglence", emoji: "🎮", tr: "Eğlence", en: "Fun" },
  { id: "davet", emoji: "📨", tr: "Davet", en: "Invite" },
  { id: "genel", emoji: "🌐", tr: "Genel", en: "General" },
  { id: "sohbet", emoji: "💬", tr: "Sohbet", en: "Chat" },
  { id: "sahip", emoji: "👑", tr: "Sahip", en: "Owner" },
  { id: "seviye", emoji: "🏆", tr: "Seviye", en: "Level" },
];

module.exports = { KOMUTLAR, KATEGORILER };
