/**
 * RiseBunny Dil Sistemi - Turkce
 * Yeni dil eklemek icin: bu dosyayi kopyalayip dil/en.js gibi yeni dosya acin,
 * dil/index.js icindeki `diller` objesine ekleyin. Hepsi bu!
 * Kullanim: const { t, getLang } = require('../dil'); t(lang, 'komut.ban.yetki')
 */
module.exports = {
  kod: "tr",
  isim: "Turkce",
  ortak: {
    hata: "Bir hata olustu, lutfen tekrar deneyin.",
    yetki: "Bu komutu kullanabilmek icin **{yetki}** yetkisine sahip olmalisin!",
    sahipSadece: "Bu komutu sadece bot sahibi kullanabilir!",
    yoneticiGerek: "Bu komut icin **Yonetici** izni gerekir.",
    premiumGerek: "Bu komut premium uyelere ozeldir. Satin almak icin `r!premium` yaz veya destek sunucumuza gel: https://dsc.gg/risebunny",
    bakimda: "Bot su anda bakimda: **{sebep}**",
    dilSec: "Lutfen gecerli bir dil belirtin: `tr` veya `en`",
    dilOk: "Diliniz basariyla **Turkce** olarak ayarlandi!",
    sunucuDilOk: "Sunucu dili basariyla **{dil}** olarak ayarlandi!",
    sunucuDilGerek: "Sunucu dilini degistirmek icin **Sunucuyu Yonet** yetkisine sahip olmalisin!",
    sunucuDilBaslik: "Sunucu Dili",
    destek: "https://dsc.gg/risebunny",
    premiumReklam: "Bu komutu kullanabilmek icin [Premium Al](https://dsc.gg/risebunny)."
  },
  yardim: {
    baslik: "RiseBunny Yardim Menusu",
    aciklama: "Hey {kullanici}! Beni kullandigin icin tesekkurler!\nPrefix: **{prefix}** | Dil: **TR** | Uyelik: **{uyelik}**\nRolumu en uste al, yoksa bazi komutlar calismaz!",
    kategoriler: "Kategoriler",
    linkler: "Linkler",
    davetEt: "Davet Et",
    destekSunucu: "Destek Sunucusu",
    guncelleme: "Guncelleme Notlari",
    premiumBaslik: "Premium Ayricaliklari",
    premiumPerks: "+%50 calisma bonusu • Cift banka faizi • Gunluk premium bonus • Premium petler • Premium koruma • Destekte oncelik",
    kategoriListe: {
      kullanici: "Kullanici komutlari",
      moderasyon: "Moderasyon komutlari",
      kayit: "Kayit sistemi",
      koruma: "Koruma sistemi",
      logo: "Logo sistemi",
      cekilis: "Cekilis sistemi",
      ticket: "Ticket sistemi",
      ekonomi: "Ekonomi sistemi",
      abone: "Abone sistemi",
      premium: "Premium sistemi",
      yapayzeka: "Yapay zeka sistemi",
      eglence: "Eglence komutlari"
    }
  },
  moderasyon: {
    banYetki: "Bu komutu kullanabilmek icin `Uyeleri Yasakla` yetkisine sahip olmalisin!",
    banEtiket: "Banlayacagin kisiyi etiketlemelisin!",
    banSahip: "Sahibimi banlayamam ;)",
    banOk: "{kullanici} adli kullanici banlandi.",
    kickYetki: "Ne yazik ki bu komutu kullanmaya yetkin yok.",
    kickEtiket: "Lutfen atilacak kisiyi etiketleyiniz!",
    kickOnay: "{kullanici} adli sahsin sunucudan atilmasini onayliyor musun?",
    kickOk: "Islem onaylandi! {kullanici} adli sahis sunucudan atildi!",
    kickIptal: "Islem iptal oldu!",
    muteOrnek: "Mutelenmesini istedigin kullaniciyi belirtmelisin. Ornek: **r!mute @RiseBunny 1saat Spam**",
    muteSure: "Kullanicinin ne kadar muteli kalacagini belirtmelisin.",
    muteSahip: "Kendi sahibime mute atamam ;)",
    silMiktar: "Silinecek mesaj sayisini belirt (1-100).",
    silOk: "{adet} mesaj silindi."
  },
  kayit: {
    isimYaz: "Lutfen **ismini yaz** ve hemen kayit islemin bitsin.",
    yasYaz: "Merhaba {isim}, simdi **yasini yaz.**",
    sadeceIsim: "**Sadece ismini yaz.** *Yasini degil.*",
    isimGerek: "**Ismini yazman gerekiyor dostum!**",
    yasSayi: "**Yasini **`(sayi)`** olarak sadece yaz.**",
    kayitOk: "Kayit basariyla tamamlandi. Iyi eglenceler **{isim}**",
    otomatikKayit: "Kayit basariyla tamamlandi. **Otomatik** olarak kayit edildin. Iyi eglenceler **{isim}**"
  },
  koruma: {
    kufurUyari: "{kullanici}, **Bu sunucuda kufur yasak!**",
    kufurLog: "{kullanici}, **Kufur etmeye calisti!**",
    reklamUyari: "{kullanici}, **Bu sunucuda reklam yapmak yasak!**",
    reklamLog: "{kullanici}, **Reklam yapmaya calisti!**",
    spamUyari: "{kullanici}, **Bu sunucuda spam yapmak yasak!**",
    acildi: "{sistem} koruma sistemi acildi.",
    kapatildi: "{sistem} koruma sistemi kapatildi."
  },
  raid: {
    embedBaslik: "🛡️ Raid Koruması",
    acildi: "Raid koruması başarıyla açıldı! Eşik: **{esik}** katılım / 10sn.",
    acildiRol: "Raid koruması başarıyla açıldı! Eşik: **{esik}** katılım / 10sn, Doğrulama Rolü: {rol}",
    kapatildi: "Raid koruması başarıyla kapatıldı.",
    durumAcik: "Durum: **Açık**\nEşik: **{esik}** katılım / 10sn\nDoğrulama Rolü: {rol}\n\nKapatmak için: `{prefix}raid kapat` veya aşağıdaki butona tıklayın.",
    durumKapali: "Durum: **Kapalı**\n\nAçmak için: `{prefix}raid aç [eşik] [@rol]` veya aşağıdaki butona tıklayın.",
    rolYok: "Yok",
    zatenAcik: "Raid koruması zaten açık!",
    zatenKapali: "Raid koruması zaten kapalı!",
    tespit: "🛡️ Raid tespit edildi! Yeni hesaplar doğrulanıyor.",
    butonAc: "Aç",
    butonKapat: "Kapat"
  },
  ekonomi: {
    yetersiz: "Yetersiz bakiye! Gereken: **{miktar}**, mevcut: **{bakiye}**.",
    paraEklendi: "{miktar} para eklendi: {kullanici}",
    transferOk: "{miktar} para {kullanici} adli kullaniciya gonderildi.",
    gunlukOk: "Gunluk odulunu aldin: **{miktar}**! Yarin tekrar gel.",
    gunlukBekle: "Gunluk odulunu zaten aldin! Kalan sure: **{sure}**",
    calisOk: "Calistin ve **{miktar}** kazandin!",
    vipGerek: "VIP almak icin {eksik} daha gerekir."
  },
  ticket: {
    kanalYok: "Biletlerin gonderilecegi kanal ayarlanmamis. Ayarlamak icin: {prefix}ticketayarla #kanal",
    kanalOk: "Biletlerin gonderilecegi kanal basariyla ayarlandi: {kanal}",
    sadeceAdmin: "Bu komutu sadece adminler kullanabilir.",
    amacSor: "Lutfen bilet acma amacini belirtin.",
    amacBaslik: "Bilet Acma Amaci",
    hosgeldin: "Hosgeldin! Yetkililer en kisa zamanda donus yapacak, lutfen sabirli ol.\nBileti kapatmak istersen: kilit",
    kapatildi: "Bilet {kullanici} tarafindan kapatildi.",
    tekrarAcildi: "Bilet {kullanici} tarafindan tekrar acildi.",
    silinecek: "Bilet 5 saniye sonra tamamen silinecek.",
    cooldown: "5 saniyede bir bilet acilabilir!"
  },
  premium: {
    aktif: "VIP uyeligin 30 gunlugune aktiflestirildi.",
    zaten: "Zaten aktif VIP uyeligin var.",
    verildi: "{kullanici} adli kullaniciya premium verildi. Sure: 30 gun.",
    silindi: "Kullanicinin premium bilgileri basariyla silindi!",
    degil: "Bu uye premium uye degil!",
    etiketle: "Premium verilecek kullaniciyi etiketleyin.",
    durum: "Premium durumun: **{durum}** | Kalan: **{kalan}**",
    aktifDurum: "Aktif",
    pasifDurum: "Pasif",
    sureDoldu: "Kullanicinin premium suresi doldu: {kullanici} ({id})"
  },
  karaliste: {
    engellisin: "RiseBunny komutlarini kullanman engellenmistir.\n**Sebep:** {sebep}",
    eklendi: "{kullanici} karalisteye eklendi. Sebep: {sebep}",
    kaldirildi: "{kullanici} karalisteden kaldirildi."
  },
  ticketPanel: {
    baslik: "Destek Talebi Olustur",
    aciklama: "Destek almak icin asagidaki butona basarak bilet acabilirsin.",
    buton: "Bilet Ac",
    modalBaslik: "Bilet acma sebebi",
    sebepEtiket: "Sebebin nedir?"
  },
  kategoriler: {
    kullanici: "Kullanıcı komutları",
    moderasyon: "Moderasyon komutları",
    kayit: "Kayıt sistemi",
    yapayzeka: "Yapay zeka sistemi",
    koruma: "Koruma sistemi",
    logo: "Logo sistemi",
    cekilis: "Çekiliş sistemi",
    ticket: "Ticket sistemi",
    ekonomi: "Ekonomi sistemi",
    abone: "Abone sistemi",
    premium: "Premium sistemi",
    eglence: "Eğlence komutları",
    davet: "Davet sistemi",
    genel: "Genel komutlar",
    sohbet: "Sohbet komutları",
    sahip: "Sahip komutları",
    seviye: "Seviye sistemi",
  },
  komutlar: {
    "abone": { aciklama: "Abone rolü verir.", kullanim: "abone @kullanıcı" },
    "abonelog": { aciklama: "Abone log kanalını ayarlar.", kullanim: "abonelog #kanal" },
    "abonerol": { aciklama: "Abone rolünü ayarlar.", kullanim: "abonerol @rol" },
    "abonerol-sistem": { aciklama: "Abone rol sistemi menüsünü gösterir.", kullanim: "abonerol-sistem" },
    "abone-yetkili": { aciklama: "Abone yetkilisi rolünü ayarlar.", kullanim: "abone-yetkili @rol" },
    "afk": { aciklama: "AFK moduna girer.", kullanim: "afk <sebep>" },
    "atatürk": { aciklama: "Atatürk resmi gönderir.", kullanim: "atatürk" },
    "pp": { aciklama: "Avatarını gösterir.", kullanim: "pp [@kullanıcı]" },
    "bakım": { aciklama: "Bakım modunu açar/kapatır. (Sahip)", kullanim: "bakım [sebep]" },
    "mağaza-yönet": { aciklama: "Site mağazası: fiyat değiştir, ürün göster/gizle (sahip).", kullanim: "mağaza-yönet" },
    "yedek": { aciklama: "croxydb'nin tüm verisini DM'e yedekler (sahip).", kullanim: "yedek" },
    "yedek-yükle": { aciklama: "Tam yedek dosyasını geri yükler (sahip).", kullanim: "yedek-yükle + dosya eki" },
    "kupon": { aciklama: "Butonlu kupon yönetimi: para/pet/premium, süreli/süresiz, bot/site (sahip).", kullanim: "kupon" },
    "kodoluştur": { aciklama: "V2 kalıcı kuponunu oluşturur veya panele yönlendirir.", kullanim: "kodoluştur [v2]" },
    "ban-koruma-sıfırla": { aciklama: "Ban korumayı sıfırlar.", kullanim: "ban-koruma-sıfırla" },
    "ban-koruma": { aciklama: "Ban korumayı açar.", kullanim: "ban-koruma #kanal" },
    "ban": { aciklama: "Belirtilen kullanıcıyı yasaklar.", kullanim: "ban @kullanıcı [sebep]" },
    "banka": { aciklama: "Banka bakiyeni gösterir.", kullanim: "banka" },
    "bansay": { aciklama: "Yasaklı üye sayısını gösterir.", kullanim: "bansay" },
    "beyazliste": { aciklama: "Kullanıcıyı karalisteden çıkarır.", kullanim: "beyazliste <ID>" },
    "çal": { aciklama: "Başka kullanıcıdan para çalar.", kullanim: "çal @kullanıcı" },
    "çalış": { aciklama: "Çalışıp para kazanırsın.", kullanim: "çalış" },
    "çek": { aciklama: "Bankadan para çeker.", kullanim: "çek <miktar>" },
    "cf": { aciklama: "Yazı-tura oyunu.", kullanim: "cf <miktar|all>" },
    "kasa-aç": { aciklama: "CS kasa açma simülasyonu.", kullanim: "kasa-aç" },
    "davet": { aciklama: "Bot davet ve destek linkleri.", kullanim: "davet" },
    "dil": { aciklama: "Bot dilini ayarlar.", kullanim: "dil <tr/en> | dil sunucu <tr/en>" },
    "emojiler": { aciklama: "Sunucudaki emojileri listeler.", kullanim: "emojiler" },
    "espri": { aciklama: "Rastgele espri yapar.", kullanim: "espri" },
    "eval": { aciklama: "Kod çalıştırır. (Sahip)", kullanim: "eval <kod>" },
    "gif-animal": { aciklama: "Rastgele hayvan gifi gönderir.", kullanim: "gif-animal" },
    "günlük": { aciklama: "Günlük ödülünü alırsın.", kullanim: "günlük" },
    "gönder": { aciklama: "Kullanıcıya para gönderir.", kullanim: "gönder @kullanıcı <miktar>" },
    "haftalık": { aciklama: "Haftalık ödülünü alırsın.", kullanim: "haftalık" },
    "hatırlat": { aciklama: "Belirtilen süre sonra hatırlatır.", kullanim: "hatırlat 10m <not>" },
    "giriş-çıkış-ayarla": { aciklama: "Giriş-çıkış kanalını ayarlar.", kullanim: "giriş-çıkış-ayarla #kanal" },
    "giriş-çıkış-kapat": { aciklama: "Giriş-çıkışı kapatır.", kullanim: "giriş-çıkış-kapat" },
    "iban": { aciklama: "IBAN oluşturur veya gösterir.", kullanim: "iban [@kullanıcı]" },
    "istatistik": { aciklama: "Bot istatistiklerini gösterir.", kullanim: "istatistik" },
    "istek": { aciklama: "Kod isteği gönderir.", kullanim: "istek <metin>" },
    "alınacak-rol": { aciklama: "Kayıtta alınacak rolü ayarlar.", kullanim: "alınacak-rol @rol" },
    "erkek-rol": { aciklama: "Erkek rolünü ayarlar.", kullanim: "erkek-rol @rol" },
    "erkek": { aciklama: "Erkek olarak kayıt eder.", kullanim: "erkek @kullanıcı isim yaş" },
    "kayıt-hg": { aciklama: "Kayıt hoşgeldin kanalını ayarlar.", kullanim: "kayıt-hg #kanal" },
    "kayıt-kanal": { aciklama: "Kayıt kanalını ayarlar.", kullanim: "kayıt-kanal #kanal" },
    "kayıtçı-rol": { aciklama: "Kayıtçı rolünü ayarlar.", kullanim: "kayıtçı-rol @rol" },
    "kız-rol": { aciklama: "Kız rolünü ayarlar.", kullanim: "kız-rol @rol" },
    "kız": { aciklama: "Kız olarak kayıt eder.", kullanim: "kız @kullanıcı isim yaş" },
    "kanal-koruma-sıfırla": { aciklama: "Kanal korumayı sıfırlar.", kullanim: "kanal-koruma-sıfırla" },
    "kanal-koruma": { aciklama: "Kanal korumayı açar.", kullanim: "kanal-koruma #kanal" },
    "karaliste-liste": { aciklama: "Karalisteyi gösterir.", kullanim: "karaliste-liste" },
    "karaliste": { aciklama: "Kullanıcıyı karalisteye alır.", kullanim: "karaliste <ID> [sebep]" },
    "para": { aciklama: "Cüzdan ve banka bilgini gösterir.", kullanim: "para [@kullanıcı]" },
    "para-sıralama": { aciklama: "Para sıralamasını gösterir.", kullanim: "para-sıralama" },
    "kick": { aciklama: "Kullanıcıyı sunucudan atar (onaylı).", kullanim: "kick @kullanıcı" },
    "kuponkullan": { aciklama: "Kupon kodunu kullanır.", kullanim: "kuponkullan <kod>" },
    "kuponoluştur": { aciklama: "Yeni kupon oluşturur.", kullanim: "kuponoluştur <miktar>" },
    "koruma": { aciklama: "Premium korumayı açar/kapatır.", kullanim: "koruma [kapat]" },
    "kullanıcibilgi": { aciklama: "Kullanıcı bilgisini gösterir.", kullanim: "kullanıcibilgi [@kullanıcı]" },
    "küfürengel": { aciklama: "Küfür filtresini açar/kapatır.", kullanim: "küfürengel" },
    "küfürlog": { aciklama: "Küfür log kanalını ayarlar.", kullanim: "küfürlog #kanal" },
    "lafat": { aciklama: "Etiketlediğin kişiye kapak yapar.", kullanim: "lafat @kullanıcı" },
    "arrow": { aciklama: "Arrow logo yapar.", kullanim: "arrow <yazı>" },
    "gold": { aciklama: "Gold logo yapar.", kullanim: "gold <yazı>" },
    "graffiti": { aciklama: "Graffiti logo yapar.", kullanim: "graffiti <yazı>" },
    "green": { aciklama: "Green logo yapar.", kullanim: "green <yazı>" },
    "mc-skin": { aciklama: "Minecraft kostümünü gösterir.", kullanim: "mc-skin <oyuncu>" },
    "mod-log": { aciklama: "Mod-log kanalını ayarlar.", kullanim: "mod-log #kanal" },
    "mute": { aciklama: "Kullanıcıyı süreli susturur.", kullanim: "mute @kullanıcı 10m [sebep]" },
    "otorol-ayarla": { aciklama: "Otorolü ayarlar.", kullanim: "otorol-ayarla @rol #kanal" },
    "otorol-mesaj": { aciklama: "Otorol mesajını ayarlar.", kullanim: "otorol-mesaj <metin>" },
    "otorol-mesaj-sıfırla": { aciklama: "Otorol mesajını sıfırlar.", kullanim: "otorol-mesaj-sıfırla" },
    "otorol-kapat": { aciklama: "Otorolü kapatır.", kullanim: "otorol-kapat" },
    "oylama": { aciklama: "Oylama başlatır.", kullanim: "oylama <metin>" },
    "para-ekle": { aciklama: "Kullanıcıya para ekler. (Yetkili)", kullanim: "para-ekle @kullanıcı <miktar>" },
    "transfer": { aciklama: "IBAN'a para transfer eder.", kullanim: "transfer <iban> <miktar>" },
    "param": { aciklama: "Para bakiyeni gösterir.", kullanim: "param" },
    "para-sil": { aciklama: "Kullanıcıdan para siler. (Yetkili)", kullanim: "para-sil @kullanıcı <miktar>" },
    "pet": { aciklama: "Pet alır veya satar.", kullanim: "pet al <tür> / pet sat <no>" },
    "petlerim": { aciklama: "Petlerini gösterir.", kullanim: "petlerim [@kullanıcı]" },
    "ping": { aciklama: "Bot gecikmesini gösterir.", kullanim: "ping" },
    "premium-al": { aciklama: "Oyun parasıyla premium alır.", kullanim: "premium-al" },
    "premium": { aciklama: "Premium durumunu gösterir.", kullanim: "premium" },
    "premium-sil": { aciklama: "Premiumu siler. (Sahip)", kullanim: "premium-sil @kullanıcı" },
    "premium-ver": { aciklama: "Premium verir. (Sahip)", kullanim: "premium-ver @kullanıcı [gün]" },
    "randompp": { aciklama: "Rastgele profil gösterir.", kullanim: "randompp" },
    "reklamengel": { aciklama: "Reklam filtresini açar/kapatır.", kullanim: "reklamengel" },
    "reklamlog": { aciklama: "Reklam log kanalını ayarlar.", kullanim: "reklamlog #kanal" },
    "rol-koruma-sıfırla": { aciklama: "Rol korumayı sıfırlar.", kullanim: "rol-koruma-sıfırla" },
    "rol-koruma": { aciklama: "Rol korumayı açar.", kullanim: "rol-koruma #kanal" },
    "bonus-ekle": { aciklama: "Davet bonusu ekler.", kullanim: "bonus-ekle @kullanıcı <sayı>" },
    "davet-kanal": { aciklama: "Davet kanalını ayarlar.", kullanim: "davet-kanal #kanal" },
    "davet-kanal-sıfırla": { aciklama: "Davet kanalını sıfırlar.", kullanim: "davet-kanal-sıfırla" },
    "davetleri-sıfırla": { aciklama: "Davetleri sıfırlar.", kullanim: "davetleri-sıfırla @kullanıcı" },
    "davetlerim": { aciklama: "Davetlerini gösterir.", kullanim: "davetlerim" },
    "davet-rol": { aciklama: "Davet rol ödülü ekler.", kullanim: "davet-rol @rol <sayı>" },
    "davet-sıfırla": { aciklama: "Davet rütbesini sıfırlar.", kullanim: "davet-sıfırla" },
    "rütbeler": { aciklama: "Davet rütbelerini listeler.", kullanim: "rütbeler" },
    "davettop": { aciklama: "Davet sıralamasını gösterir.", kullanim: "davettop" },
    "sa-as": { aciklama: "SA-AS sistemini açar/kapatır.", kullanim: "sa-as aç/kapat" },
    "say": { aciklama: "Sunucu bilgilerini gösterir.", kullanim: "say" },
    "shard": { aciklama: "Shard bilgisini gösterir.", kullanim: "shard" },
    "sil": { aciklama: "Mesajları siler.", kullanim: "sil <1-100>" },
    "snipe": { aciklama: "Son silinen mesajı gösterir.", kullanim: "snipe" },
    "sohbet-aç": { aciklama: "Sohbeti açar.", kullanim: "sohbet-aç" },
    "sohbet-kapat": { aciklama: "Sohbeti kapatır.", kullanim: "sohbet-kapat" },
    "sonmesaj": { aciklama: "Son mesajı gösterir.", kullanim: "sonmesaj" },
    "soygun": { aciklama: "Soygun yapar.", kullanim: "soygun @kullanıcı" },
    "spam-kapat": { aciklama: "Spam korumayı kapatır.", kullanim: "spam-kapat" },
    "spamkoruma": { aciklama: "Spam korumayı açar/kapatır.", kullanim: "spamkoruma" },
    "sunucukur": { aciklama: "Sunucuyu kurar.", kullanim: "sunucukur" },
    "sunuculara": { aciklama: "Bot davet linkini gösterir.", kullanim: "sunuculara" },
    "sürelirol": { aciklama: "Süreli rol verir.", kullanim: "sürelirol @kullanıcı @rol <süre>" },
    "sürem": { aciklama: "VIP süreni gösterir.", kullanim: "sürem" },
    "ticket": { aciklama: "Destek bileti açar.", kullanim: "ticket <sebep> / ticket panel" },
    "ticketayarla": { aciklama: "Ticket kanalını ayarlar.", kullanim: "ticketayarla #kanal" },
    "tkm": { aciklama: "Taş-kağıt-makas oynar.", kullanim: "tkm <taş/kağıt/makas>" },
    "komutlar": { aciklama: "Toplam komut sayısını gösterir.", kullanim: "komutlar" },
    "unbanall": { aciklama: "Tüm yasakları kaldırır.", kullanim: "unbanall" },
    "uyarı": { aciklama: "Kullanıcıyı uyarır.", kullanim: "uyarı @kullanıcı [sebep]" },
    "vip": { aciklama: "VIP süreni gösterir.", kullanim: "vip" },
    "vipsistemler": { aciklama: "VIP sistemlerini listeler.", kullanim: "vipsistemler" },
    "y-kayıt-erkek": { aciklama: "YZ ile erkek kaydı yapar.", kullanim: "y-kayıt-erkek @rol" },
    "y-kayıt-kadın": { aciklama: "YZ ile kadın kaydı yapar.", kullanim: "y-kayıt-kadın @rol" },
    "ykayıt-kanal": { aciklama: "YZ kayıt kanalını ayarlar.", kullanim: "ykayıt-kanal #kanal" },
    "ykayıt-kapat": { aciklama: "YZ kaydı kapatır.", kullanim: "ykayıt-kapat" },
    "ykayıt-sistem": { aciklama: "YZ kayıt menüsünü gösterir.", kullanim: "ykayıt-sistem" },
    "ykayıt-tag": { aciklama: "YZ kayıt tagını ayarlar.", kullanim: "ykayıt-tag <tag>" },
    "ykayıt-kayıtsız": { aciklama: "YZ kayıtsız rolünü ayarlar.", kullanim: "ykayıt-kayıtsız @rol" },
    "y-koruma": { aciklama: "YZ korumayı açar/kapatır.", kullanim: "y-koruma" },
    "y-otosistem": { aciklama: "YZ kayıt sistemini otomatik kurar.", kullanim: "y-otosistem" },
    "ekonomi": { aciklama: "Ekonomi yardım menüsü.", kullanim: "ekonomi" },
    "kayıtsistemi": { aciklama: "Kayıt yardım menüsü.", kullanim: "kayıtsistemi" },
    "korumasistemi": { aciklama: "Koruma yardım menüsü.", kullanim: "korumasistemi" },
    "kullanıcı": { aciklama: "Kullanıcı yardım menüsü.", kullanim: "kullanıcı" },
    "logosistemi": { aciklama: "Logo yardım menüsü.", kullanim: "logosistemi" },
    "moderasyon": { aciklama: "Moderasyon yardım menüsü.", kullanim: "moderasyon" },
    "çekilişsistemi": { aciklama: "Çekiliş yardım menüsü.", kullanim: "çekilişsistemi" },
    "yardım": { aciklama: "Yardım menüsünü gösterir.", kullanim: "yardım [kategori]" },
    "yatır": { aciklama: "Bankaya para yatırır.", kullanim: "yatır <miktar>" },
    "zarat": { aciklama: "Zar atar.", kullanim: "zarat" },
    "başlat": { aciklama: "Çekiliş başlatır.", kullanim: "başlat #kanal <süre> <sayı> <ödül>" },
    "sonlandır": { aciklama: "Çekilişi bitirir.", kullanim: "sonlandır <mesajID>" },
    "reroll": { aciklama: "Çekilişi yeniden çeker.", kullanim: "reroll <mesajID>" },
    "öneri": { aciklama: "Öneri gönderir.", kullanim: "öneri <metin>" },
    "üyedurum": { aciklama: "Üye sayısını gösterir.", kullanim: "üyedurum" },
    "seviye": { aciklama: "Seviyeni ve XP kartını gösterir.", kullanim: "seviye [@kullanıcı]" },
    "seviye-ödül": { aciklama: "Seviye ödüllerini listeler ve rol ödülü tanımlar.", kullanim: "seviye-ödül [liste|rol <seviye> @rol|sil <seviye>]" },
    "seviye-sıralama": { aciklama: "En yüksek levelli 10 kullanıcıyı resimli gösterir.", kullanim: "seviye-sıralama" },
    "günlük-ödül": { aciklama: "Art arda gün sayısına göre büyüyen günlük ödül.", kullanim: "günlük-ödül" },
    "anket-gelişmiş": { aciklama: "Butonlu/tepkili, süreli anket başlatır.", kullanim: "anket-gelişmiş <süre> <soru> | <seçenek1> | <seçenek2>" },
    "çekiliş-şart": { aciklama: "Davet sayısı veya rol şartlı çekiliş.", kullanim: "çekiliş-şart #kanal <süre> <kazanan> <ödül> --davet <sayı> / --rol @rol" },
    "raid-koruma": { aciklama: "Kısa sürede çok katılım olursa otomatik doğrulama ve koruma yapar.", kullanim: "raid aç [eşik] [@rol] | raid kapat | raid" },
    "raid": { aciklama: "Kısa sürede çok katılım olursa otomatik doğrulama ve koruma yapar.", kullanim: "raid aç [eşik] [@rol] | raid kapat | raid" },
    "market": { aciklama: "Kullanıcıların pet alıp sattığı pazar.", kullanim: "market liste | sat <petNo> <fiyat> | al <id> | iptal <id>" },
    "not": { aciklama: "Kişisel not defteri.", kullanim: "not ekle <metin> | liste | sil <no> | temizle" },
    "isim-log": { aciklama: "İsim değişikliklerini loglar.", kullanim: "isim-log #kanal | kapat" },
    "çevir": { aciklama: "Metni başka dile çevirir.", kullanim: "çevir <hedef> <metin>" },
    "slot": { aciklama: "Slot makinesi oyunu.", kullanim: "slot <miktar|all>" },
    "blackjack": { aciklama: "Blackjack (21) oyunu.", kullanim: "blackjack <miktar|all>" },
    "rulet": { aciklama: "Rulet oyunu.", kullanim: "rulet <miktar> <kırmızı/siyah/yeşil/sayı>" },
    "faiz": { aciklama: "Bankadaki parana günlük faiz.", kullanim: "faiz" },
    "piyango": { aciklama: "Piyango bileti al ve havuzu kazan.", kullanim: "piyango [al | çek]" },
    "meslek": { aciklama: "Meslek seç ve çalışarak para kazan.", kullanim: "meslek [seç <meslek> | çalış]" },
    "envanter": { aciklama: "Tüm eşyalarını ve istatistiklerini gösterir.", kullanim: "envanter" },
    "premium-panel": { aciklama: "Premium ayrıcalıklarını gösterir.", kullanim: "premium-panel" },
    "kasa": { aciklama: "Çalınamayan kişisel kasa.", kullanim: "kasa [yatır <miktar> | çek <miktar>]" },
    "günlük-bonus": { aciklama: "Premium üyelere özel günlük bonus.", kullanim: "günlük-bonus" },
  },
  sistem: {
    yonetici: "Bu komutu kullanabilmek için **Yönetici** yetkisine sahip olmalısın!",
    mesajYonet: "Bu komut için Mesajları Yönet izni gerekir.",
    sunucuYonet: "Bu komutu kullanabilmek için **Sunucuyu Yönet** iznine sahip olmalısın!",
    sunucuSahibi: "Bu komutu kullanabilmek için **Sunucu Sahibi** olmalısın!",
    yetkiYok: "Bu komutu kullanabilmek için gerekli yetkiye sahip değilsin.",
    kullaniciBelirt: "Bir kullanıcı etiketlemelisin.",
    rolBelirt: "Bir rol etiketlemelisin.",
    kanalBelirt: "Bir kanal etiketlemelisin.",
    acildi: "{sistem} açıldı.",
    kapatildi: "{sistem} kapatıldı.",
    ayarlandi: "{sistem} başarıyla ayarlandı!",
    sifirlandi: "{sistem} başarıyla sıfırlandı!",
    ayarlanmamis: "{sistem} ayarlanmamış!",
    belirt: "{sistem} belirtmelisin!",
    premiumBaslik: "Premium Üye Değilsiniz",
    hataBaslik: "**HATA**",
    sebep: "Sebep",
    kullanici: "Kullanıcı",
    kanal: "Kanal",
    mesaj: "Mesaj",
    sonuc: "Sonuç",
    eylem: "Eylem",
    isim: "İsim",
    bilinmiyor: "Bilinmiyor"
  },
  kayitSistem: {
    kayitciGerek: "Bu komutu kullanabilmen için {rol} rolüne sahip olman lazım!",
    kanalOzel: "Bu komutu sadece {kanal} kanalında kullanabilirsin!",
    kurulumYok: "Kayıt sistemi tam kurulmamış! Önce rolleri ve kanalı ayarlayın.",
    erkekKayit: "Erkek Kayıt",
    kizKayit: "Kız Kayıt",
    kayitEden: "Kayıt eden yetkili",
    kayitEdilen: "Kayıt edilen kullanıcı",
    isim: "İsmi",
    yas: "Yaşı",
    isimBelirt: "İsmini belirtmelisin!",
    yasBelirt: "Yaşını belirtmelisin!",
    rolSec: "{tur} rolünü belirtiniz!",
    rolAyarlandi: "{tur} rolü başarıyla {rol} olarak ayarlandı!",
    rolSifirlandi: "{tur} rolü başarıyla sıfırlandı!",
    kanalAyarlandi: "Kayıt olunacak kanal {kanal} olarak ayarlandı!",
    kanalSifirlandi: "Kayıt olunacak kanal başarıyla sıfırlandı!",
    kanalBelirt: "Kayıt olunacak kanalı belirtiniz!",
    hgAyarlandi: "Hoş geldin kanalı {kanal} olarak ayarlandı!",
    hgSifirlandi: "Hoş geldin kanalı başarıyla sıfırlandı!",
    hgBelirt: "Hoş geldin kanalı belirtiniz!",
    alinacakAyarlandi: "Kayıt olunca otomatik alınacak rol başarıyla {rol} olarak ayarlandı!",
    alinacakSifirlandi: "Kayıt olunca otomatik alınacak rol sıfırlandı!",
    alinacakBelirt: "Kayıt olunca alınacak rolü belirtiniz!",
    kayitciAyarlandi: "Kayıtçı rolü başarıyla {rol} olarak ayarlandı!",
    kayitciSifirlandi: "Kayıtçı rolü başarıyla sıfırlandı!",
    kayitciBelirt: "Ayarlayacağınız kayıtçı rolünü belirtiniz!",
    erkek: "Erkek",
    kiz: "Kız",
    kayitci: "Kayıtçı",
    alinacak: "Alınacak rol",
    kayitBasarili: "{uye} başarıyla kayıt edildi! İyi eğlenceler!"
  },
};
